import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

export default function DisclaimerPage() {
  return (
    <>
      <Navbar />
      <main className="bg-white">

        {/* Hero banner */}
        <div className="bg-amber-50 border-b-2 border-amber-300">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10 text-center">
            <div className="w-14 h-14 bg-amber-100 border-2 border-amber-300 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-7 h-7 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
              </svg>
            </div>
            <p className="text-xs font-bold text-amber-700 uppercase tracking-widest mb-3">Legal</p>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-zinc-900 mb-4">
              Important Legal Disclaimer
            </h1>
            <p className="text-base text-zinc-600 max-w-xl mx-auto leading-relaxed">
              Please read this disclaimer carefully before using DealEdge AI.
              By using this tool, you acknowledge and agree to everything stated below.
            </p>
          </div>
        </div>

        {/* Main disclaimer content */}
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">

          {/* Big warning box */}
          <div className="bg-red-50 border-2 border-red-300 rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 bg-red-100 rounded-xl flex items-center justify-center shrink-0 mt-0.5">
                <svg className="w-5 h-5 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                </svg>
              </div>
              <div>
                <p className="text-base font-extrabold text-red-800 mb-2">
                  NOT Financial, Investment, or Legal Advice
                </p>
                <p className="text-sm text-red-700 leading-relaxed">
                  DealEdge AI is a <strong>calculation and estimation tool only</strong>. Nothing on this platform
                  constitutes financial advice, investment advice, real estate advice, tax advice, or legal advice
                  of any kind. We are not a licensed financial advisor, real estate broker, attorney, or accountant.
                </p>
              </div>
            </div>
          </div>

          {/* Disclaimer sections */}
          {[
            {
              icon: '📊',
              title: '1. Tool Outputs Are Estimates Only',
              text: `All deal scores, profit projections, ROI calculations, AI decisions ("BUY," "NEGOTIATE," "PASS"),
              suggested offer prices, red flag alerts, and any other outputs generated by DealEdge AI are
              mathematical estimates based solely on the numbers you input. They are NOT guarantees of actual
              profit, loss, or performance. Real-world results will vary — often significantly — due to market
              conditions, hidden costs, contractor overruns, title issues, financing changes, and hundreds of
              other factors this tool cannot account for.`,
            },
            {
              icon: '🚫',
              title: '2. We Do Not Encourage You to Buy or Invest in Anything',
              text: `DealEdge AI does not recommend, promote, or encourage you to purchase any specific property,
              make any specific investment, or take any specific financial action. A "BUY" signal from our
              AI is a mathematical output — not a recommendation to spend your money. A "PASS" signal does
              not mean the deal is necessarily bad. You are solely responsible for your own investment
              decisions. We take no position on whether any particular deal is right or wrong for you.`,
            },
            {
              icon: '⚠️',
              title: '3. Always Verify With Licensed Professionals',
              text: `Before making any real estate investment decision, you must independently verify all information
              and consult with licensed professionals including but not limited to: a licensed real estate agent
              or broker, a certified public accountant (CPA) or tax advisor, a real estate attorney,
              a licensed general contractor, a professional property inspector, and a licensed mortgage
              lender or financial advisor. DealEdge AI does not replace any of these professionals.`,
            },
            {
              icon: '💸',
              title: '4. You Assume All Financial Risk',
              text: `Real estate investing involves substantial risk, including the possible loss of your entire
              investment. Past estimates or outputs generated by this tool do not guarantee future results.
              Market conditions, interest rates, property values, and economic conditions can change rapidly
              and without warning. You acknowledge that you are solely responsible for any financial decisions
              you make and any resulting gains or losses. Miami Global Investments Group LLC bears zero
              financial liability for investment outcomes based on this tool.`,
            },
            {
              icon: '🔢',
              title: '5. Input Accuracy Is Your Responsibility',
              text: `The quality of our outputs depends entirely on the accuracy of the data you enter.
              Garbage in, garbage out. If you enter incorrect purchase prices, ARV estimates, repair costs,
              or other inputs, the results will be misleading. We do not verify, validate, or independently
              research any numbers you provide. You are responsible for ensuring that all inputs reflect
              accurate, current market data obtained from qualified sources.`,
            },
            {
              icon: '🏠',
              title: '6. No Representation on Property Values or Market Conditions',
              text: `DealEdge AI does not appraise properties, does not access MLS data, does not analyze
              local market conditions, and does not have access to current comparable sales ("comps").
              The "After Repair Value" (ARV) you enter is your own estimate. We make no representation
              as to what any property is actually worth or what it will sell for after renovation.
              Always obtain a professional appraisal or BPO (Broker Price Opinion) before making offers.`,
            },
            {
              icon: '📋',
              title: '7. SMS Messages Are Templates Only',
              text: `Any seller SMS messages generated by the Offer Message feature are
              generic templates for convenience purposes only. They have not been reviewed by a licensed
              real estate attorney and do not constitute legally binding documents or professional legal
              advice. Any actual real estate purchase contracts must be reviewed and executed with the
              assistance of a licensed real estate attorney in the applicable jurisdiction.`,
            },
            {
              icon: '⚖️',
              title: '8. Complete Limitation of Liability',
              text: `To the maximum extent permitted by applicable law, Miami Global Investments Group LLC,
              its officers, directors, employees, agents, affiliates, and successors shall not be liable
              for any direct, indirect, incidental, special, exemplary, consequential, or punitive damages
              of any kind — including but not limited to financial losses, lost profits, lost opportunities,
              or emotional distress — arising from your use of DealEdge AI or any investment decision made
              in reliance on its outputs, even if we have been advised of the possibility of such damages.`,
            },
            {
              icon: '🤝',
              title: '9. Your Agreement',
              text: `By using DealEdge AI, you explicitly acknowledge that: (1) you have read and understood
              this disclaimer in full; (2) you are using this tool for informational and educational purposes
              only; (3) you will not make any investment decision based solely on outputs from this tool;
              (4) you accept full and sole responsibility for your investment decisions and their outcomes;
              and (5) you release Miami Global Investments Group LLC from any and all claims, damages,
              or liabilities arising from your use of this platform.`,
            },
          ].map((section) => (
            <div key={section.title} className="bg-zinc-50 border border-zinc-200 rounded-2xl p-6">
              <div className="flex items-start gap-4">
                <span className="text-2xl shrink-0 mt-0.5">{section.icon}</span>
                <div>
                  <h2 className="text-base font-extrabold text-zinc-900 mb-2">{section.title}</h2>
                  <p className="text-sm text-zinc-600 leading-relaxed">{section.text}</p>
                </div>
              </div>
            </div>
          ))}

          {/* Final summary box */}
          <div className="bg-zinc-900 rounded-2xl p-6 text-white">
            <p className="text-sm font-extrabold uppercase tracking-wider text-zinc-400 mb-3">Summary</p>
            <p className="text-lg font-bold text-white mb-4 leading-snug">
              DealEdge AI is a calculator. Not a financial advisor. Not a real estate broker. Not an attorney.
            </p>
            <div className="space-y-2">
              {[
                'Use it to do quick math — not to make final decisions.',
                'Always verify numbers with professionals before investing.',
                'We are not responsible for your investment outcomes.',
                'You and you alone are responsible for your financial decisions.',
              ].map((point) => (
                <div key={point} className="flex items-start gap-2.5">
                  <svg className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                  </svg>
                  <p className="text-sm text-zinc-300">{point}</p>
                </div>
              ))}
            </div>
          </div>

          <p className="text-xs text-zinc-400 text-center pb-4">
            Last updated: May 6, 2026 · Miami Global Investments Group LLC · Miami, Florida
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
